name: Generate Changelog

on:
  push:
    branches:
      - main  # or your main branch
  pull_request:
    branches:
      - main  # or your main branch

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install git-chglog
        run: |
          # Download the release file first
          curl -L -o git-chglog_0.14.0_Linux_x86_64.tar.gz https://github.com/git-chglog/git-chglog/releases/download/v0.14.0/git-chglog_0.14.0_Linux_x86_64.tar.gz
          
          # Check if the file is in gzip format
          file git-chglog_0.14.0_Linux_x86_64.tar.gz
          
          # Extract the file if it's valid
          tar -xvzf git-chglog_0.14.0_Linux_x86_64.tar.gz
          
          # Move the binary to a proper location
          sudo mv git-chglog /usr/local/bin

      - name: Generate changelog
        run: |
          git-chglog -o CHANGELOG.md --next-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
